spring.application.name=crudSpringBoot
server.port=8090


spring.datasource.url=jdbc:mysql://localhost:3306/student_crud_db
spring.datasource.username=root
spring.datasource.password=212173314
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
